# Generated by Django 4.2.1 on 2023-06-10 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0003_rename_servicecreateddata_clientservices_servicecreateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
