# Generated by Django 4.1.7 on 2023-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.IntegerField()),
                ('hostname', models.CharField(max_length=200)),
                ('deviceType', models.CharField(max_length=200)),
                ('popName', models.CharField(max_length=250)),
                ('popLatitude', models.BigIntegerField()),
                ('pioLatitude', models.BigIntegerField()),
                ('modelName', models.CharField(max_length=250)),
                ('districtname', models.CharField(max_length=250)),
                ('regionName', models.CharField(max_length=250)),
                ('provinceName', models.CharField(max_length=250)),
                ('branchName', models.CharField(max_length=250)),
                ('hyperVisor', models.CharField(max_length=250)),
            ],
        ),
    ]
