# Generated by Django 4.1.7 on 2023-03-14 09:08

import Models.client_services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srvType', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClientServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('primaryContactName', models.CharField(max_length=250)),
                ('primaryContactNumber', models.BigIntegerField(validators=[Models.client_services.mobile_number_validation])),
                ('primaryContactEmail', models.EmailField(max_length=254)),
                ('secondaryContactName', models.CharField(max_length=250)),
                ('secondaryContactNumber', models.BigIntegerField(validators=[Models.client_services.mobile_number_validation])),
                ('secondaryContactEmail', models.EmailField(max_length=254)),
                ('serviceStatus', models.BooleanField(default=True)),
                ('serviceCreatedData', models.DateTimeField()),
                ('hostId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Models.hosts')),
                ('srvType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Models.servicetypes')),
            ],
        ),
    ]
