# Generated by Django 4.1.7 on 2023-03-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_servicetypes_clientservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='hostId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Models.hosts'),
        ),
    ]
