# Generated by Django 4.1.7 on 2023-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_applications_hostid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='serverControl',
            field=models.CharField(choices=[('Subisu', 'Subisu'), ('Vendor', 'Vendor'), ('Both', 'Both')], max_length=150),
        ),
        migrations.AlterField(
            model_name='applications',
            name='sourceCode',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('IN HOUSE', 'IN HOUSE')], max_length=200),
        ),
    ]
