# Generated by Django 4.1.7 on 2023-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_alter_applications_servercontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaccess',
            name='applicationAccessMethod',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile App', 'Mobile App'), ('CLI', 'CLI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationaccess',
            name='applicationAccountStatus',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default=True),
        ),
    ]
