# Generated by Django 4.1.7 on 2023-03-29 07:17

from django.db import migrations, models
import django.db.models.deletion
import subisu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Activity Title')),
                ('maintenanceWindow', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.TextField(blank=True, verbose_name='Reasons')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefits for Layer')),
                ('impact', models.TextField(blank=True, verbose_name='Impact')),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(auto_now=True, verbose_name='Activity End Time')),
                ('activities', models.TextField(max_length=500, verbose_name='Activities')),
                ('created', models.TimeField(auto_now_add=True, verbose_name='Activity Created At')),
                ('otherEmails', models.EmailField(blank=True, max_length=254, null=True)),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close'), ('In Progress', 'In Progress')], default='Open', max_length=20)),
                ('sendEmail', models.BooleanField(default=False, help_text='Send Email Notification to Department', verbose_name='Send Email')),
                ('contact', models.ForeignKey(help_text='Select units you want to send mail to', null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.units')),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Datacenter Name')),
                ('address', models.CharField(max_length=200, verbose_name='Datacenter Address')),
                ('contact', models.BigIntegerField(verbose_name='Datacenter Contact')),
                ('remarks', models.TextField(blank=True, help_text='Leave remarks for the datacenter', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(blank=True, editable=False, help_text='Enter Host Name', max_length=200, null=True, verbose_name='Host Name')),
                ('remarks', models.TextField(blank=True, help_text='Leave a remark', null=True, verbose_name='Remark')),
                ('created', models.TimeField(auto_now_add=True, verbose_name='Created At')),
                ('hostId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Models.hosts', verbose_name='Select Host')),
                ('srvType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Models.servicetypes', verbose_name='Select Service Type')),
            ],
        ),
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poaDetails', models.TextField(max_length=250, verbose_name='POA Details')),
                ('poaEntry', models.TimeField(auto_now_add=True, verbose_name='POA Entry')),
                ('sendEmail', models.BooleanField(default=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity')),
                ('fieldEngineer', models.ManyToManyField(blank=True, to='Models.staffs', verbose_name='Select Field Engineers')),
                ('units', models.ManyToManyField(blank=True, to='Models.units', verbose_name='Send emails to Units')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailBody', models.TextField(blank=True, null=True)),
                ('logTime', models.TimeField(auto_now_add=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=200, validators=[subisu.models.mobile_no_length], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('status', models.BooleanField(default=True, verbose_name='Client Status')),
                ('registerDate', models.TimeField(auto_now_add=True, verbose_name='Register Date')),
                ('srvid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.service', verbose_name='Select Service')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, editable=False, max_length=500, null=True)),
                ('commentBy', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('timeStamp', models.TimeField(auto_now_add=True, null=True)),
                ('actId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.activities')),
            ],
        ),
    ]
