# Generated by Django 4.1.7 on 2023-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activity Start Time'),
        ),
    ]
