# Generated by Django 4.1.7 on 2023-02-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=250)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dcID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('srvType', models.IntegerField()),
                ('hostName', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.host')),
            ],
        ),
    ]
