# Generated by Django 4.1.7 on 2023-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0002_alter_activities_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='otherEmails',
            field=models.TextField(blank=True, help_text='Add other emails separated by spaces', null=True),
        ),
    ]
