# Generated by Django 4.1.7 on 2023-02-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0003_servicetype_alter_service_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='srvType',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
