# Generated by Django 4.1.7 on 2023-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0004_alter_activities_otheremails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.TimeField(auto_now=True, verbose_name='Activity Created At'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Activity Start Time'),
        ),
    ]
