# Generated by Django 4.1.7 on 2023-05-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0005_alter_activities_created_alter_activities_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='ETA',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
