# Generated by Django 4.1.7 on 2023-05-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0006_activities_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.TimeField(auto_now_add=True, verbose_name='Activity Created At'),
        ),
    ]
