# Generated by Django 4.1.7 on 2023-02-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0006_alter_servicetype_id_clientcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('ETA', models.CharField(max_length=200)),
                ('endTime', models.DateTimeField(auto_now=True)),
                ('activities', models.TextField(max_length=500)),
                ('created', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='registerDate',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('registerDate', models.TimeField(auto_now_add=True)),
                ('deptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.department')),
            ],
        ),
    ]
