# Generated by Django 4.1.7 on 2023-05-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0007_alter_activities_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='maintenanceWindow',
        ),
    ]
