# Generated by Django 4.1.7 on 2023-02-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0007_activities_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poaDetails', models.TextField(max_length=250)),
                ('poaEntry', models.TimeField(auto_now_add=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities')),
                ('fieldEngineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificaiton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('sendStatus', models.BooleanField(default=False)),
                ('logTime', models.TimeField(auto_now_add=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities')),
            ],
        ),
    ]
