# Generated by Django 4.1.7 on 2023-02-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0009_alter_activities_id_alter_clientcontact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activities',
            field=models.TextField(max_length=500, verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.TimeField(auto_now_add=True, verbose_name='Activity Created At'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='endTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Activity End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activity Start Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Activity Title'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='mobile',
            field=models.CharField(max_length=200, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='registerDate',
            field=models.TimeField(auto_now_add=True, verbose_name='Register Date'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='srvid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.service', verbose_name='Select Service'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Client Status'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Datacenter Address'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='contact',
            field=models.BigIntegerField(verbose_name='Datacenter Contact'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Datacenter Name'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='remarks',
            field=models.TextField(blank=True, help_text='Leave remarks for the datacenter', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Department Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Department Status'),
        ),
        migrations.AlterField(
            model_name='emailnotificaiton',
            name='activityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity'),
        ),
        migrations.AlterField(
            model_name='emailnotificaiton',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailnotificaiton',
            name='sendStatus',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='host',
            name='dcID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.datacenter', verbose_name='Select Datacenter'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=250, verbose_name='Internet Protocol Address (IP Addres)'),
        ),
        migrations.AlterField(
            model_name='host',
            name='remarks',
            field=models.TextField(blank=True, help_text='Leave remakrs for the host', null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='poa',
            name='activityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity'),
        ),
        migrations.RemoveField(
            model_name='poa',
            name='fieldEngineer',
        ),
        migrations.AlterField(
            model_name='poa',
            name='poaDetails',
            field=models.TextField(max_length=250, verbose_name='POA Details'),
        ),
        migrations.AlterField(
            model_name='poa',
            name='poaEntry',
            field=models.TimeField(auto_now_add=True, verbose_name='POA Entry'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.TimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.host', verbose_name='Select Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hostName',
            field=models.CharField(blank=True, help_text='Enter Host Name', max_length=200, null=True, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='remarks',
            field=models.TextField(blank=True, help_text='Leave a remark', null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='service',
            name='srvType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.servicetype', verbose_name='Select Service Type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='deptId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.department', verbose_name='Select Department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Staff Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Staff Mobile No'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='registerDate',
            field=models.TimeField(auto_now_add=True, verbose_name='Registered At'),
        ),
        migrations.AddField(
            model_name='poa',
            name='fieldEngineer',
            field=models.ManyToManyField(blank=True, to='subisu.staff', verbose_name='Select Field Engineers'),
        ),
    ]
