# Generated by Django 4.1.7 on 2023-05-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0010_alter_activities_endtime_alter_activities_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='ETA',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
