# Generated by Django 4.1.7 on 2023-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0010_alter_activities_activities_alter_activities_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='srvid',
        ),
        migrations.RemoveField(
            model_name='emailnotificaiton',
            name='activityId',
        ),
        migrations.RemoveField(
            model_name='host',
            name='dcID',
        ),
        migrations.RemoveField(
            model_name='poa',
            name='activityId',
        ),
        migrations.RemoveField(
            model_name='poa',
            name='fieldEngineer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hostId',
        ),
        migrations.RemoveField(
            model_name='service',
            name='srvType',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='deptId',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='ClientContact',
        ),
        migrations.DeleteModel(
            name='Datacenter',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmailNotificaiton',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Poa',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
