# Generated by Django 4.1.7 on 2023-05-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0011_alter_activities_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activity Created At'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
    ]
