# Generated by Django 4.1.7 on 2023-02-17 08:11

from django.db import migrations, models
import django.db.models.deletion
import subisu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subisu', '0011_remove_clientcontact_srvid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Activity Title')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='Activity Start Time')),
                ('ETA', models.CharField(max_length=200)),
                ('endTime', models.DateTimeField(auto_now=True, verbose_name='Activity End Time')),
                ('activities', models.TextField(max_length=500, verbose_name='Activities')),
                ('created', models.TimeField(auto_now_add=True, verbose_name='Activity Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Datacenter Name')),
                ('address', models.CharField(max_length=200, verbose_name='Datacenter Address')),
                ('contact', models.BigIntegerField(verbose_name='Datacenter Contact')),
                ('remarks', models.TextField(blank=True, help_text='Leave remarks for the datacenter', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Department Email')),
                ('status', models.BooleanField(default=True, verbose_name='Department Status')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, verbose_name='Host Name')),
                ('ip', models.CharField(max_length=250, validators=[subisu.models.ip_address], verbose_name='Internet Protocol Address (IP Addres)')),
                ('remarks', models.TextField(blank=True, help_text='Leave remakrs for the host', null=True, verbose_name='Remarks')),
                ('dcID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.datacenter', verbose_name='Select Datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Staff Email')),
                ('mobile', models.CharField(max_length=15, validators=[subisu.models.mobile_no_length], verbose_name='Staff Mobile No')),
                ('registerDate', models.TimeField(auto_now_add=True, verbose_name='Registered At')),
                ('deptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.department', verbose_name='Select Department')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(blank=True, help_text='Enter Host Name', max_length=200, null=True, verbose_name='Host Name')),
                ('remarks', models.TextField(blank=True, help_text='Leave a remark', null=True, verbose_name='Remark')),
                ('created', models.TimeField(auto_now_add=True, verbose_name='Created At')),
                ('hostId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subisu.host', verbose_name='Select Host')),
                ('srvType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.servicetype', verbose_name='Select Service Type')),
            ],
        ),
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poaDetails', models.TextField(max_length=250, verbose_name='POA Details')),
                ('poaEntry', models.TimeField(auto_now_add=True, verbose_name='POA Entry')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity')),
                ('fieldEngineer', models.ManyToManyField(blank=True, to='subisu.staff', verbose_name='Select Field Engineers')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificaiton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('sendStatus', models.IntegerField(verbose_name='Status')),
                ('logTime', models.TimeField(auto_now_add=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=200, validators=[subisu.models.mobile_no_length], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('status', models.BooleanField(default=True, verbose_name='Client Status')),
                ('registerDate', models.TimeField(auto_now_add=True, verbose_name='Register Date')),
                ('srvid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.service', verbose_name='Select Service')),
            ],
        ),
    ]
