# Generated by Django 4.2.1 on 2023-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0012_alter_activities_created_alter_activities_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close'), ('Work in Progress', 'Work in Progress')], default='Open', max_length=20),
        ),
    ]
