# Generated by Django 4.1.7 on 2023-02-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hostId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='subisu.host', verbose_name='Select Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hostName',
            field=models.CharField(blank=True, editable=False, help_text='Enter Host Name', max_length=200, null=True, verbose_name='Host Name'),
        ),
    ]
