# Generated by Django 4.1.7 on 2023-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0013_alter_service_hostid_alter_service_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.IntegerField(choices=[('Close', 0), ('Open', 1)], default=0),
        ),
    ]
