# Generated by Django 4.2.1 on 2023-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0013_alter_activities_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytable',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitytable',
            name='commentBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
