# Generated by Django 4.1.7 on 2023-02-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0014_activities_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('sendStatus', models.BooleanField(verbose_name='Status')),
                ('logTime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Open')], default='Close'),
        ),
        migrations.DeleteModel(
            name='EmailNotificaiton',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='activityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subisu.activities', verbose_name='Select Activity'),
        ),
    ]
