# Generated by Django 4.1.7 on 2023-02-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0015_emailnotification_alter_activities_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='status',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sendStatus',
            field=models.BooleanField(editable=False, verbose_name='Status'),
        ),
    ]
