# Generated by Django 4.2.1 on 2023-06-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_staffs_user'),
        ('subisu', '0015_remove_activities_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='empId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.staffs'),
        ),
    ]
