# Generated by Django 4.1 on 2023-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0018_emailnotification_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity_Table',
            new_name='ActivityTable',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sendStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close'), ('In Progress', 'In Progress')], default='Open', max_length=25, verbose_name='Status'),
        ),
    ]
