# Generated by Django 4.1.7 on 2023-02-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0020_activities_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytable',
            name='actId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subisu.activities'),
        ),
    ]
