# Generated by Django 4.1.7 on 2023-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0021_alter_activitytable_actid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytable',
            name='timeStamp',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
