# Generated by Django 4.1.7 on 2023-02-22 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subisu', '0022_activitytable_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytable',
            name='commentBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
