# Generated by Django 4.1.7 on 2023-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0023_alter_activitytable_commentby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytable',
            name='commentBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
