# Generated by Django 4.1.7 on 2023-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0024_alter_activitytable_commentby'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Close', 'Close'), ('In Progress', 'In Progress')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activity End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(verbose_name='Activity Start Time'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sendStatus',
            field=models.CharField(default='Open', max_length=25, verbose_name='Status'),
        ),
    ]
