# Generated by Django 4.1.7 on 2023-02-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0025_activities_status_alter_activities_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='sendEmail',
            field=models.BooleanField(default=False, help_text='Send Email to Department', verbose_name='Send Email'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='endTime',
            field=models.DateTimeField(verbose_name='Activity End Time'),
        ),
        migrations.AlterField(
            model_name='activitytable',
            name='comment',
            field=models.TextField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitytable',
            name='commentBy',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sendStatus',
            field=models.CharField(max_length=25, verbose_name='Status'),
        ),
    ]
