# Generated by Django 4.1.7 on 2023-02-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0026_activities_sendemail_alter_activities_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='message',
            new_name='emailBody',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='sendStatus',
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='sendTo',
        ),
    ]
