# Generated by Django 4.1 on 2023-03-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0028_activities_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='units',
            field=models.ManyToManyField(blank=True, to='Models.units'),
        ),
    ]
