# Generated by Django 4.1 on 2023-03-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0029_alter_activities_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='dcID',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='deptId',
        ),
        migrations.AlterField(
            model_name='poa',
            name='fieldEngineer',
            field=models.ManyToManyField(blank=True, to='Models.staffs', verbose_name='Select Field Engineers'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hostId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Models.hosts', verbose_name='Select Host'),
        ),
        migrations.AlterField(
            model_name='service',
            name='srvType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Models.servicetypes', verbose_name='Select Service Type'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
