# Generated by Django 4.1 on 2023-03-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0030_remove_host_dcid_remove_staff_deptid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='sendEmail',
            field=models.BooleanField(default=True),
        ),
    ]
