# Generated by Django 4.1 on 2023-03-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0031_poa_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='units',
            field=models.ManyToManyField(blank=True, to='Models.units', verbose_name='Send emails to Units'),
        ),
    ]
