# Generated by Django 4.1.7 on 2023-03-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0032_poa_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='ETA',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='units',
        ),
        migrations.AddField(
            model_name='activities',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits for Layer'),
        ),
        migrations.AddField(
            model_name='activities',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.units'),
        ),
        migrations.AddField(
            model_name='activities',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Impact'),
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='maintenanceWindow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Reasons'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='endTime',
            field=models.DateTimeField(auto_now=True, verbose_name='Activity End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='sendEmail',
            field=models.BooleanField(default=False, help_text='Send Email Notification to Department', verbose_name='Send Email'),
        ),
        migrations.AddField(
            model_name='activities',
            name='Comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
