# Generated by Django 4.1.7 on 2023-03-29 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0033_remove_activities_eta_remove_activities_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 43, 54, 741949, tzinfo=datetime.timezone.utc)),
        ),
    ]
