# Generated by Django 4.1.7 on 2023-03-29 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0034_activities_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='contact',
            field=models.ForeignKey(help_text='Select units you want to send mail to ||', null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.units'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 47, 43, 46869, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
