# Generated by Django 4.1.7 on 2023-03-29 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0035_alter_activities_contact_alter_activities_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 3, 48, 20, 372215, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
