# Generated by Django 4.1.7 on 2023-03-29 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subisu', '0036_alter_activities_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='maintenanceWindow',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 4, 47, 43, 318992, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
