# Generated by Django 4.1.7 on 2023-03-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
        ('subisu', '0037_alter_activities_maintenancewindow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='contact',
            field=models.ForeignKey(help_text='Select units you want to send mail to', null=True, on_delete=django.db.models.deletion.CASCADE, to='Models.units'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
